export * from './menu.interface';
export * from './nav.interface';
export * from './text-block.interface';
export * from './image-sharp.interface';
export * from './gql-collection.interface';
export * from './media-extra.interface';
export * from './paragraph.interface';
export * from './blogs.interface';
export * from './articles.interface';
